using Content.Shared._Stories.TTS; // Stories-TTS
using Robust.Shared.GameStates;

namespace Content.Shared._RMC14.Megaphone;

[RegisterComponent, NetworkedComponent, AutoGenerateComponentState] // Stories-TTS
[Access(typeof(RMCMegaphoneSystem))]
// Stories-TTS-Start
public sealed partial class RMCMegaphoneComponent : Component
{
    /// <summary>
    /// Stories: Multiplier applied to the base voice range (normal voice range is 10).
    /// </summary>
    [DataField, AutoNetworkedField]
    public float VoiceRangeMultiplier = 1.5f;

    /// <summary>
    /// Stories: Client playback gain multiplier. Values above 1.5 saturate the audio source.
    /// </summary>
    [DataField("ttsVolumeMultiplier"), AutoNetworkedField]
    public float TTSVolumeMultiplier = 1.5f;

    /// <summary>
    /// Stories: Multiplier applied to TTS range. Defaults to the same range as the text broadcast.
    /// </summary>
    [DataField("ttsRangeMultiplier"), AutoNetworkedField]
    public float TTSRangeMultiplier = 1.5f;

    /// <summary>
    /// Stories: Keep the megaphone loud near its speaker before distance attenuation begins.
    /// </summary>
    [DataField("ttsReferenceDistance"), AutoNetworkedField]
    public float TTSReferenceDistance = 4f;

    /// <summary>
    /// Stories: Reduce positional attenuation so the megaphone remains intelligible at range.
    /// </summary>
    [DataField("ttsRolloffFactor"), AutoNetworkedField]
    public float TTSRolloffFactor = 0.25f;

    /// <summary>
    /// Stories: Server-side audio effects applied to TTS generated by the megaphone.
    /// </summary>
    [DataField("ttsAudioEffects"), AutoNetworkedField]
    public TTSAudioEffect AudioEffects = TTSAudioEffect.Megaphone;
}
// Stories-TTS-End
